### ISSUE TITLE
reproductivity

### ISSUE THREAD

**Issue by db-beep** [PYangLab/scCCESS#2]
Hi,
I want to reproduce the pictures and experimental effects in the paper,Can you provide some drawing codes？

**Comment by db-beep** [comment]
Visual clustering results code not found！

**Comment by yulijia** [comment]
Hi db-beep, 

Sorry for the delay. 

You can visualise the clustering results by applying a dimension-reduction method such as t-sne to the original data and color by cluster.

For boxplot and barplot, you can visualize the result by using `ggplot2` package.
